### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by thesukantadey** [SamAinsworth/reproduce-asplos2020-gc-paper#1]
Hi,

while compiling the Guardian Council simulator and the Guardian Kernels using 

`./build.sh` command, errors are generated. Please see the below image for the error. I am using Ubuntu 16.04 LTS and all the dependencies are installed. Can you help me out with this?

![Screenshot 2021-02-03 at 12 26 21 AM](https://user-images.githubusercontent.com/3337377/106649241-4bcbcc80-65b7-11eb-8df7-21bf39387e5a.png)

**Comment by SamAinsworth** [comment]
Hi Sukanta,

The issue appears to be that the gem5 simulator we used was compiled on an older GCC that doesn't throw errors of the form 

-Werror=class-memaccess

Whereas your newer compiler does.

These warnings can be safely suppressed, by adding the following to the SConscript in the gem5-guardian folder, by adding this line after line 662, with the same indentation as line 662:

main.Append(CXXFLAGS=['-Wno-error=class-memaccess'])    

Does that fix the problem?

Thanks,
Sam

**Comment by thesukantadey** [comment]
Hi Sam,

Thanks a lot for your help.

Yes, it is working. Although, it is showing many other similar warnings, but it can be suppressed following same procedure. 

Thanks again.

~Sukanta

**Comment by SamAinsworth** [comment]
Glad to hear it! Incidentally, do you know which version of GCC you were using to compile it? I'll update the Readme to try to fend off the error in future.

**Comment by thesukantadey** [comment]
My gcc version is: `aarch64-linux-gnu-gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609`

I had to append the following two lines after 662 line in the file `/reproduce-asplos2020-gc-paper-master/gem5-guardian/SConstruct`

`  main.Append(CXXFLAGS=['-Wno-error=class-memaccess'])`
 `  main.Append(CXXFLAGS=['-Wno-error=ignored-qualifiers'])`

**Comment by SamAinsworth** [comment]
Great, thanks -- I've added something on troubleshooting to the readme. Are you compiling gem5 to run on an Arm system then, rather than x86?

**Comment by thesukantadey** [comment]
No, my system is `x86_64/Intel`. `gcc` version of my system is `8.4.0`. However, the `build.sh` script uses the `aarch64-linux-gnu-gcc` for compilation of the files, so I thought the errors might have been generated due to that compiler. 

For more information of my system, please see this image,
![Screenshot 2021-02-03 at 11 36 53 PM](https://user-images.githubusercontent.com/3337377/106789809-bc86ed80-6678-11eb-89b8-3bb899d941b9.png)

**Comment by SamAinsworth** [comment]
Ah okay, great, thanks. Yes, it's the newer version of x86's GCC, to compile gem5, that caused the error. Good to know -- presumably this will be quite common -- so thank you for catching it!
